export const PART_DESCRIPTIONS = {
  Soma: {
    name: "Soma",
    desc: "The soma (cell body, or perikaryon) is the part of the neuron that contains the nucleus and most of the biosynthetic organelles. Its main job is to integrate the electrical and biochemical signals arriving from the dendrites, maintain the cell, and supply proteins and membranes to the whole neuron. In light microscopy, soma diameter varies strongly by cell class: for example cerebellar granule cell bodies are often on the order of roughly 5–8 micrometres, many cortical pyramidal somata about 10–30 micrometres, and large motor or Purkinje neurons can reach roughly tens of micrometres up to about 100 micrometres or more in exceptional cases. There is no single “standard” size because form follows circuit role. The soma is also where much of the metabolic load of transcription and translation is concentrated, so it is tightly coupled to long-term changes in synaptic strength.",
  },
  Nucleus: {
    name: "Nucleus",
    desc: "The nucleus stores the genome and runs transcription: DNA to RNA, processing of RNAs, and export to the cytoplasm for translation. In neurons the nucleus is usually round to oval and, in many medium-sized central neurons, on the order of about 5–10 micrometres in diameter, with large neurons reaching larger nuclear diameters (roughly up to the mid‑teens of micrometres or more). The nuclear envelope separates transcription and splicing from translation in the cytosol. Because mature neurons are post‑mitotic in most brain regions, the nucleus is not preparing for division; instead it sustains decades of gene-expression programs that support plasticity, repair, and metabolism. Chromatin organization in neurons responds to activity and experience, linking nuclear function directly to learning-related processes.",
  },
  Dendrites: {
    name: "Dendrites",
    desc: "Dendrites are branched processes that receive most excitatory and inhibitory synaptic input and route those signals toward the soma and axon initial segment. Near the soma, proximal dendrite shafts are comparatively thick, often on the order of about 1–5 micrometres, then taper into thinner distal branches that can be well below one micrometre across. A single dendritic tree can span from tens of micrometres up to roughly a millimetre or more depending on neuron type and species. Functionally, dendrites perform passive spread of synaptic potentials, and in many cells also active boosting (dendritic spikes, voltage-gated channels) so input location and timing matter for output. They are therefore the main anatomical substrate for integration of thousands of converging synapses.",
  },
  "Dendritic Spine": {
    name: "Dendritic Spine",
    desc: "A dendritic spine is a small postsynaptic protrusion from a dendrite shaft that typically hosts one excitatory synapse on its head. Measured by electron microscopy in mammalian cortex and hippocampus, spine heads are commonly about 0.5–1.0 micrometres in diameter (with variation by spine class), spine necks often about 0.05–0.3 micrometres in diameter, and neck lengths roughly about 0.05–2 micrometres depending on whether the spine is thin, mushroom-shaped, or stubby. The neck acts as a biochemical and electrical bottleneck: it partly isolates the head so calcium and signalling molecules in one spine compartment do not instantly equilibrate with the whole dendrite. Spines remodel (grow, shrink, appear, disappear) with activity, which is why they are central to models of learning and memory at the synaptic level.",
  },
  "Axon Hillock": {
    name: "Axon Hillock",
    desc: "The axon hillock is the tapering region where the soma transitions into the axon. Functionally it is continuous with the axon initial segment just downstream, which is the usual site where action potentials are initiated because of a very high density of voltage-gated sodium channels. The hillock plus initial segment together span on the order of tens of micrometres along the axon in many cell types (roughly about 20–100 micrometres is a commonly cited range for the initial segment extent, cell-dependent). The job of this region is to compare summed synaptic drive arriving from dendrites and soma against threshold and, when threshold is crossed, to trigger a regenerative sodium spike that propagates down the axon. Pathology that lowers threshold or adds persistent sodium current here or in the initial segment can contribute to hyperexcitability.",
  },
  Axon: {
    name: "Axon",
    desc: "The axon is a single long process specialized for rapid, reliable transmission of action potentials from the initiation zone toward presynaptic terminals. Axonal length ranges from sub‑millimetre local interneurons to well over a metre for human lower‑motor‑neuron axons from spinal cord to muscle. Diameter also spans a wide range: large myelinated peripheral motor axons can be on the order of roughly 10–20 micrometres, whereas many cortical axons are much thinner, often roughly sub‑micrometre to a few micrometres. Conduction velocity rises with diameter and with myelination; myelinated axons in mammals can conduct on the order of tens of metres per second, whereas thin unmyelinated C fibres conduct slowly. The axon also transports organelles, mRNA, and membrane proteins along microtubules in both directions.",
  },
  "Myelin Sheath": {
    name: "Myelin Sheath",
    desc: "In the peripheral nervous system, the myelin sheath is a stack of Schwann-cell membranes wrapped concentrically around an axon segment, rich in lipids and compacted proteins such as myelin protein zero. One Schwann cell typically myelinates one internodal segment; along human peripheral nerve, internodal lengths are often on the order of roughly hundreds of micrometres up to a couple of millimetres depending on fibre class and position. The sheath electrically insulates the axon membrane under it so that the action potential does not need to regenerate continuously along that stretch. That reduces capacitance per unit length and allows saltatory conduction between nodes of Ranvier, which greatly increases speed and metabolic efficiency compared with an unmyelinated fibre of similar outer diameter. Demyelinating diseases disrupt this geometry and slow or block conduction.",
  },
  "Node of Ranvier": {
    name: "Node of Ranvier",
    desc: "A node of Ranvier is a short gap between two myelin internodes where the axonal plasma membrane is exposed and densely packed with voltage-gated sodium channels (and other channels). Along the fibre, each node is typically on the order of about 0.5–2 micrometres long in the longitudinal direction (species- and fibre-type-dependent). Functionally, the arriving action potential depolarizes the node strongly enough to launch a fresh spike that electrotonically invades the next internode until the next node fires; that sequential regeneration is saltatory conduction. Nodes are therefore not decorative gaps but the repeating stations where the wave is actively rebuilt. If nodal channel clusters or paranodal junctions fail, conduction can block or become intermittent.",
  },
  "Axon Terminal": {
    name: "Axon Terminal",
    desc: "The axon terminal is the presynaptic specialization at the end of an axon (or of an axon branch) where the neuron converts an arriving action potential into neurotransmitter release. Terminals are often organized as strings of swellings; individual synaptic boutons in central circuits are commonly on the order of about 1–5 micrometres across, though sizes vary widely by connection type. Inside, terminals contain synaptic vesicles (tens of nanometres in diameter), active-zone machinery, mitochondria, and calcium channels. When an action potential invades, voltage-gated calcium channels open, local calcium rises on the microsecond-to-millisecond scale, and vesicles fuse at the active zone, releasing transmitter into the synaptic cleft. That chemical signal is what actually couples most neurons to their targets.",
  },
  "Synaptic Bouton": {
    name: "Synaptic Bouton",
    desc: "A synaptic bouton is a bulb-shaped presynaptic ending that faces a postsynaptic partner across a narrow synaptic cleft (often on the order of tens of nanometres wide at central synapses). Boutons package neurotransmitter in synaptic vesicles (classic small clear vesicles are typically tens of nanometres in diameter) and position them at the active zone, a protein-rich membrane specialization aligned opposite postsynaptic receptors. A single axon can form from one to many thousands of boutons depending on cell identity. Each bouton can operate with its own short-term plasticity (facilitation, depression) based on vesicle pools and calcium dynamics, so the neuron is not one uniform output device but a distributed set of release sites.",
  },
  Mitochondria: {
    name: "Mitochondria",
    desc: "Mitochondria are organelles with outer and inner membranes that carry out oxidative phosphorylation to regenerate ATP and also participate in calcium handling, lipid metabolism, and signalling pathways. In neurons they are often elongated and transported along dendrites and axons to match metabolic demand; lengths on the order of about 0.5–5 micrometres are common in tissue images, with diameters typically sub‑micrometre to about one micrometre depending on orientation and fusion–fission state. The brain consumes a large fraction of whole-body resting glucose; mitochondria supply much of that ATP for ion pumping, vesicle cycling, and cytoskeletal transport. Mitochondrial dysfunction, altered motility, or impaired quality control are implicated in several neurodegenerative and neuropsychiatric conditions.",
  },
  "Nissl Body": {
    name: "Nissl Body",
    desc: "Nissl bodies are basophilic clumps in the soma and proximal dendrites that correspond to stacks of rough endoplasmic reticulum (RER) studded with ribosomes, together with free polysomes. They do not have a single fixed “length and width” like a whole organelle because they are distributed factories: many separate RER cisternae interleaved with the Golgi region. Their function is protein synthesis for membrane channels, receptors, structural proteins, and enzymes needed for neurotransmission and plasticity. After axonal injury, the orderly distribution of Nissl substance can disperse in chromatolysis, which is a cytological sign that the neuron has shifted gene expression toward stress and repair programs.",
  },
  "Schwann Cell": {
    name: "Schwann Cell",
    desc: "Schwann cells are the myelinating glia of the peripheral nervous system. One myelinating Schwann cell typically wraps one segment of one axon, producing a myelin internode whose length along the axon is on the order of hundreds of micrometres up to about a millimetre or more depending on fibre calibre and location. The cell body itself is on the order of tens of micrometres. Schwann cells spiral many layers of membrane around the axon, excluding cytoplasm between wraps to form compact myelin. They also form non-myelinating ensheathing Schwann cells around small axons. After peripheral nerve crush or cut, Schwann cells help clear debris and basal lamina tracks and release trophic signals that support axon regrowth, which is one reason peripheral axons can regenerate better than many central axons.",
  },
};
